//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

// #import <objc/NSObject.h>

// #import "PDRefundPaymentViewControllerDelegate-Protocol.h"
// #import "PDSDKImageManagerDelegate-Protocol.h"
// #import "SKProductsRequestDelegate-Protocol.h"
// #import "UNUserNotificationCenterDelegate-Protocol.h"
// #import "ZlDelegate-Protocol.h"
#import "PDSDKInitView.h"

// @protocol OS_dispatch_source, PDSDKDelegate;

@interface PDSDKBaseManager
{
    _Bool _FlagInitSuccess;
    _Bool _FlagLoginSuccess;
    _Bool _bInitedIm;
    _Bool _showRefundView;
    _Bool _requestedRefundInfo;
    NSString *_logincustomparams;
    NSString *_Logoutcustomparams;
    NSString *_paycustomparams;
    id _delegate;
    PDSDKInitView *_PdinitView;
    NSString *_pdsdkuid;
    NSString *_PromotingRegisterID;
    NSDictionary *_launchOptions;
    NSMutableArray *_goodslist;
    // NSObject<OS_dispatch_source> *_timer;
}

+ (id)sharedInstance;
// @property(retain, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
@property(nonatomic, getter=isRequestedRefundInfo) _Bool requestedRefundInfo; // @synthesize requestedRefundInfo=_requestedRefundInfo;
@property(nonatomic, getter=isShowRefundView) _Bool showRefundView; // @synthesize showRefundView=_showRefundView;
@property(retain, nonatomic) NSMutableArray *goodslist; // @synthesize goodslist=_goodslist;
@property(retain, nonatomic) NSDictionary *launchOptions; // @synthesize launchOptions=_launchOptions;
@property(nonatomic) _Bool bInitedIm; // @synthesize bInitedIm=_bInitedIm;
@property(retain, nonatomic) NSString *PromotingRegisterID; // @synthesize PromotingRegisterID=_PromotingRegisterID;
@property(retain, nonatomic) NSString *pdsdkuid; // @synthesize pdsdkuid=_pdsdkuid;
@property(retain, nonatomic) PDSDKInitView *PdinitView; // @synthesize PdinitView=_PdinitView;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *paycustomparams; // @synthesize paycustomparams=_paycustomparams;
@property(retain, nonatomic) NSString *Logoutcustomparams; // @synthesize Logoutcustomparams=_Logoutcustomparams;
@property(retain, nonatomic) NSString *logincustomparams; // @synthesize logincustomparams=_logincustomparams;
@property(nonatomic) _Bool FlagLoginSuccess; // @synthesize FlagLoginSuccess=_FlagLoginSuccess;
@property(nonatomic) _Bool FlagInitSuccess; // @synthesize FlagInitSuccess=_FlagInitSuccess;
@end
