
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//#import "RMStoreObserver-Protocol.h"
//#import "RMStoreTransactionPersistor-Protocol.h"

//@class NSString, SKPayment;
// @protocol ZlDelegate;

@interface ZlIndexPayment
{
    id _delegate;
    SKPayment *_promotingPayment;
}

//+ (void)ZlPaymentChangeGameStatue;
//+ (id)sharedInstance;
@property(retain, nonatomic) SKPayment *promotingPayment; // @synthesize promotingPayment=_promotingPayment;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
//- (void)ZlCheckPaymentLoad;
//- (void)ZlPaymentStartGame;
//- (void)printflogWithCmbiWithId:(id)arg1 withOrderId:(id)arg2;
//- (void)printGameEvent:(id)arg1;
//- (void)verifyNewAppStoreOrderWithModel:(id)arg1 isShowToast:(_Bool)arg2 block:(CDUnknownBlockType)arg3;
//- (void)verifyOrderWithModel:(id)arg1 withCallBack:(_Bool)arg2;
//- (id)getOrderFromunknowList:(id)arg1;
//- (void)saveTransactionAndVerifyOrder:(id)arg1;
//- (void)doRestoreServer:(id)arg1;
//- (void)saveOrderInfoWithStateDeferred:(id)arg1;
//- (void)saveOrderInfo:(id)arg1 goodsRgid:(id)arg2;
//- (void)ZlOrderPatchLoaclDb:(_Bool)arg1;
//- (void)storePromotingTransactionsPaymentCallback:(id)arg1;
//- (void)storeRestoreTransactionsFinished:(id)arg1;
//- (void)storeRestoreTransactionsFailed:(id)arg1;
//- (void)storeRefreshReceiptFinished:(id)arg1;
//- (void)storeRefreshReceiptFailed:(id)arg1;
//- (void)storeProductsRequestFinished:(id)arg1;
//- (void)storeProductsRequestFailed:(id)arg1;
//- (void)storePaymentTransactionFinished:(id)arg1;
//- (void)storePaymentTransactionFailed:(id)arg1;
//- (void)persistTransaction:(id)arg1;
//- (void)ZlPayMentWithAppStore:(id)arg1 promotingFlag:(_Bool)arg2;
//- (void)ZlVerifyPayCurrency:(id)arg1 localeCountryCode:(id)arg2 info:(id)arg3 promotingFlag:(_Bool)arg4;
//- (void)ZlPaymentWithAppStore:(id)arg1 promotingFlag:(_Bool)arg2;
//- (void)ZlAddPayment:(id)arg1 promotingFlag:(_Bool)arg2;
//- (void)ZlRestore;
//- (void)ZlPaymentInit;
//
//// Remaining properties
//@property(readonly, copy) NSString *debugDescription;
//@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
//@property(readonly) Class superclass;

@end

